twist_mux:
  ros__parameters:
    topics:
      auto:
        topic   : auto
        timeout : 0.5
        priority: 1
      # joystick control
      twist_teleop:
        topic   : twist_teleop
        timeout : 0.5
        priority: 10
    locks:
      pause:
        topic: pause
        timeout: 0.0
        # Same priority as joystick control, so it'll not block it.
        priority: 10
      emergency:
        topic   : emergency
        timeout : 0.0
        priority: 255